version: '3'

services:
  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    volumes:
      - './proxy/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "80:80"  # Прокси-сервер будет слушать на порту 80
    restart: unless-stopped

  dashy:
    container_name: dashy
    image: lissy93/dashy
    volumes:
      - './dashy/config.yml:/app/user-data/conf.yml'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s