services:
  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './ssl:/etc/ssl'  # Add this line
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:  # Add this block
      - dashy
      - uptime-kuma
      - syncthing

  dashy:
    container_name: dashy
    image: lissy93/dashy
    volumes:
      - './dashy/config.yml:/app/user-data/conf.yml'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /syncthing:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
  
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8181:8080
      - 8282:8443
    environment:
      PUBLIC_DNS: draw.plasticfire.tech
      ORGANISATION_UNIT: Mobile
      ORGANISATION: PlasticFireTech
      CITY: Tomsk
      STATE: Tomsk
      COUNTRY_CODE: ru
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s