version: '3'

services:
  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    volumes:
      - './proxy/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "80:80"  # Прокси-сервер будет слушать на порту 80
    restart: unless-stopped

  dashy:
    container_name: dashy
    image: lissy93/dashy
    volumes:
      - './dashy/config.yml:/app/user-data/conf.yml'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
      # TODO: Needs manual UI switch
      # https://github.com/VueTorrent/VueTorrent/wiki/Installation#using-lsio-docker-mod
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /qbittorrent/appdata:/config
      - /qbittorent/downloads:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped
