pageInfo:
  title: PlasticFire Lab
sections:
  - name: Remote Services
    icon: far fa-rocket
    items:
      - title: Monitor
        url: https://monitor.remote.plasticfire.tech
      - title: Syncthing
        url: https://sync.remote.plasticfire.tech
